
"use strict";this.EXPORTED_SYMBOLS=["AppConstants"];let AppConstants=Object.freeze({
 NIGHTLY_BUILD:true,RELEASE_BUILD:false,ACCESSIBILITY:true,

MOZILLA_OFFICIAL:true,MOZ_OFFICIAL_BRANDING:false,MOZ_SERVICES_HEALTHREPORT:false,MOZ_DEVICES:false,MOZ_SAFE_BROWSING:true,MOZ_TELEMETRY_REPORTING:true,MOZ_WEBRTC:true,MOZ_APP_VERSION:"39.0a1",ANDROID_PACKAGE_NAME:"org.mozilla.b2g_",});